/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FibonacciJNI */

#ifndef _Included_FibonacciJNI
#define _Included_FibonacciJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     FibonacciJNI
 * Method:    fibonacci
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_FibonacciJNI_fibonacci
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
